---
version: "2.1"
services:
  robotix:
    image: severchyk/robotix:focal
    container_name: robotix
    privileged: true #optional
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - SUBFOLDER=/ #optional
      - KEYBOARD=en-us-qwerty #optional
    volumes:
      - /root/config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 80:3000
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "2gb" #optional
    restart: unless-stopped